In [1]:
import pandas as pd

# Load the CSV file
file_path = 'dataset.csv'
data = pd.read_csv(file_path, header=None)

# Assign column names based on the documentation
data.columns = ['MQ2', 'MQ9', 'MQ135', 'MQ137', 'MQ138', 'MG811', 'Activity']


In [2]:
print(data.info())
print(data.describe())
print(data['Activity'].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1845 entries, 0 to 1844
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MQ2       1845 non-null   int64
 1   MQ9       1845 non-null   int64
 2   MQ135     1845 non-null   int64
 3   MQ137     1845 non-null   int64
 4   MQ138     1845 non-null   int64
 5   MG811     1845 non-null   int64
 6   Activity  1845 non-null   int64
dtypes: int64(7)
memory usage: 101.0 KB
None
               MQ2          MQ9        MQ135        MQ137        MQ138  \
count  1845.000000  1845.000000  1845.000000  1845.000000  1845.000000   
mean    587.458537   653.465583  1166.036856  1609.279675  1302.121951   
std     190.456217   173.360131   208.791130   118.820436   279.456215   
min     263.000000   346.000000   753.000000  1323.000000   773.000000   
25%     430.000000   517.000000   995.000000  1508.000000  1086.000000   
50%     551.000000   622.000000  1162.000000  1610.000000  1264.000000  

In [3]:
X = data[['MQ2', 'MQ9', 'MQ135', 'MQ137', 'MQ138', 'MG811']]
y = data['Activity']

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [5]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [6]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.964769647696477
              precision    recall  f1-score   support

           1       1.00      0.98      0.99       119
           2       0.95      0.96      0.96       103
           3       0.93      0.95      0.94        39
           4       0.95      0.95      0.95       108

    accuracy                           0.96       369
   macro avg       0.96      0.96      0.96       369
weighted avg       0.97      0.96      0.96       369

[[117   2   0   0]
 [  0  99   0   4]
 [  0   1  37   1]
 [  0   2   3 103]]


In [8]:
X_test.shape

(369, 6)

In [10]:
X_test.head()

MQ2  MQ9  MQ135  MQ137  MQ138  MG811
1805  417  528    989   1625   1151   2204
444   956  956   1557   1813   1744   1976
75    451  548    931   1516   1110   2485
1676  548  641   1277   1636   1172   2159
1692  564  665   1248   1650   1191   2144

In [16]:
first_row = X_test.iloc[0].values.reshape(1, -1)

print(first_row, y_test.iloc[0])

[[ 417  528  989 1625 1151 2204]] 1


In [15]:
model.predict(first_row)

/home/lahiru/.local/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [18]:
import joblib
joblib.dump(model, 'random_forest_model.pkl')

['random_forest_model.pkl']